### ISSUE TITLE
npm start no go

### ISSUE THREAD

**Issue by d1b1** [scaphold-io/hacker-news-tutorial#2]
/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-relay-plugin/lib/invariant.js:24
    throw new Error(util.format.apply(util, [format].concat(args)));
    ^

Error: Invalid introspection data supplied to `getBabelRelayPlugin()`. The resulting schema is not an object with a `__schema` property.
    at invariant (/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-relay-plugin/lib/invariant.js:24:11)
    at getSchema (/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-relay-plugin/lib/getBabelRelayPlugin.js:178:3)
    at getBabelRelayPlugin (/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-relay-plugin/lib/getBabelRelayPlugin.js:38:16)
    at Object.<anonymous> (/Users/ssmith/Documents/scaphold/hacker-news-tutorial/build/babelRelayPlugin.js:14:18)
    at Module._compile (module.js:409:26)
    at loader (/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js](/Users/ssmith/Documents/scaphold/hacker-news-tutorial/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by vning93** [comment]
Thanks for raising an issue here, and apologies for this not working. What command are you running that yields this issue? All you need to do is run `npm install` and then `npm start`.

**Comment by vning93** [comment]
I just updated the repo so it doesn't include the unnecessary files to update the schema anymore. I think that may have been your problem. The schema does not need to be downloaded / cached on the client side.

**Comment by d1b1** [comment]
That fixes it. Thanks the demo runs now.

Researching solutions for a startup, and found scaphold via PH.

**Comment by vning93** [comment]
Awesome, feel free to join our [Slack Community channel](https://scapholdslackin.herokuapp.com) if you have any more questions. I'm typically online there and can field any questions you may have as they come up.

Also, I'm here more about the startup you're trying to build.

Cheers!
